---
title: "Report"
author: "Bill Chung"
date: \today
output: 
  html_document:
    css: "style.css"
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: false
      number_sections: true
      fig_caption: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.width=12, 
	fig.height=8
)
s <- Sys.time()
source("r/get_lib.R")
```

# Overall statistics

```{r cars}
mydata <- "~/Projects/2022/2022 Global Marketing Rebecca/clean_data/2821878_Cepheid_TgtList_all_with_names.csv"
product_code <- "~/Projects/2022/2022 Global Marketing Rebecca/clean_data/code_description.csv"


df <- fread(mydata)
codes <- fread(product_code)

##########################################################################
# Find correlation for all 
##########################################################################
M0 <- cor(df[,`NFCT DS BV RNA VAG FLU ALG`:`NFCT DS BACT&FNG GRAM NEG`])
M0[is.na(M0)] <- 0
ut<-upper.tri(M0)

#making it to a long format
df_cor <- data.frame(
            row = rownames(M0)[row(M0)[ut]],
            column = rownames(M0)[col(M0)[ut]],
            cor = (M0)[ut]
)

colnames(df_cor) <- c("product1","product2","cor")
```

```{r}
summary <- data.frame(
  year = c("MAT 2020-Nov", "MAT 2020-Nov","MAT 2021-Nov", "MAT 2021-Nov"),
  percent = c("Top 5%", "All","Top 5%", "All"),
  units = c(83950579, 98836744,94906562,110563462),
  number_of_npi = c(20289,433747,23430,443264)
)

summary %>% kable("pipe")

p1<- summary %>% ggplot(aes(x=percent, y = units, fill = year)) + 
     geom_bar(stat = "identity") +facet_wrap(~year)

p2<- summary %>% ggplot(aes(x=percent, y = number_of_npi, fill = year)) + 
     geom_bar(stat = "identity") +facet_wrap(~year)

p1/p2
```


## Referring COT-FAC-TYPE

```{r}
p1 <- df %>% group_by(timeperiod,referring_cot_facility_type) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(referring_cot_facility_type,-N), y = N, fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

p2 <- df %>% group_by(timeperiod,referring_cot_facility_type) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(referring_cot_facility_type,-N), y = log(N), fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p2)  
```


## Location of care

```{r}
p1 <- df %>% group_by(timeperiod,location_of_care) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(location_of_care,-N), y = N, fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

p2 <- df %>% group_by(timeperiod,location_of_care) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(location_of_care,-N), y = log(N), fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p2)  
```

## Cot_Facility_Type (Rendering)

```{r}
p1 <- df %>% group_by(timeperiod,cot_facility_type) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(cot_facility_type,-N), y = N, fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

p2 <- df %>% group_by(timeperiod,cot_facility_type) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(cot_facility_type,-N), y = log(N), fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p2)  
```

## Referring Specialty

```{r}
p1 <- df %>% group_by(timeperiod,referring_specialty) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(referring_specialty,-N), y = N, fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

p2 <- df %>% group_by(timeperiod,referring_specialty) %>% 
  summarise(N = n()) %>% 
  ggplot(aes(x=reorder(referring_specialty,-N), y = log(N), fill = timeperiod)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p2)  
```




# TOTAL CLAIMS 

## by year and types of product

```{r}
# colnames(df)

# unique(df$metrictype)

DF_BY_PRODUCT <- df %>% group_by(timeperiod,metrictype,paytype) %>% 
  summarise(across(`NFCT DS BV RNA VAG FLU ALG`:`NFCT DS BACT&FNG GRAM NEG`,sum))

# colnames(DF_BY_PRODUCT)

by_product_melt <- reshape2::melt(DF_BY_PRODUCT, id.vars = c("timeperiod","metrictype","paytype"),
                          variable_name = "Product",
                          value.name = "units")


# head(by_product_melt)

by_product_melt %>% ggplot(aes(x=metrictype, y = units, fill = paytype)) + 
                    geom_bar(stat = "identity") + facet_wrap(~timeperiod)


by_product_melt %>% group_by(timeperiod,metrictype,paytype) %>% summarise(UNITS_SOLD = sum(units))
```

## BY PROUDUCT TYPE

### HIV NON-MOLECULAR (SCREENING)

```{r}
######################################################################
# code provided by rebecaa 4/18/2022
######################################################################
hiv_non_molecular <- c(86701, 86702, 86703,87389,87390,87391,87806)
g1 <- codes %>% filter(code %in% hiv_non_molecular) %>% select(code,des)
# by_product_melt %>% filter(variable %in% g1$des)

p1 <- df_cor %>% filter(product1 %in% g1$des) %>% filter(cor > 0.1) %>%  
           ggplot(aes(x=product1, y = product2, fill = cor)) + 
           geom_tile() + scale_fill_gradient(low="white", high="blue")  +
           theme_ipsum() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

```

### HIV MOLECULAR (molecular Dx, monitoring)

```{r}

hiv_molecular <- c(87534,87535,87536,87537,87538)
g2 <- codes %>% filter(code %in% hiv_molecular) %>% select(code,des)
# by_product_melt %>% filter(variable %in% g2$des)

p1 <- df_cor %>% filter(product1 %in% g2$des) %>% filter(cor > 0.1) %>%  
           ggplot(aes(x=product1, y = product2, fill = cor)) + 
           geom_tile() + scale_fill_gradient(low="white", high="blue")  +
           theme_ipsum() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)
```

### HPV (diagnosis)

```{r}
hpv <- c(87623,87624,87625)
g3 <- codes %>% filter(code %in% hpv) %>% select(code,des)
# by_product_melt %>% filter(variable %in% g3$des)

p1 <- df_cor %>% filter(product1 %in% g3$des) %>% filter(cor > 0.1) %>%  
           ggplot(aes(x=product1, y = product2, fill = cor)) + 
           geom_tile() + scale_fill_gradient(low="white", high="blue")  +
           theme_ipsum() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

```

### HCV non-molecular (screening) 


```{r}
hcv_non_molecular <- c(86803,86804)
g4 <- codes %>% filter(code %in% hcv_non_molecular) %>% select(code,des)
# by_product_melt %>% filter(variable %in% g4$des)

p1 <- df_cor %>% filter(product1 %in% g4$des) %>% filter(cor > 0.1) %>%  
           ggplot(aes(x=product1, y = product2, fill = cor)) + 
           geom_tile() + scale_fill_gradient(low="white", high="blue")  +
           theme_ipsum() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

```

### HCV Molecular (diagnosis and monitoring)

```{r}
hcv_molecular <- c(87520,87521,87522)
g5 <- codes %>% filter(code %in% hcv_molecular) %>% select(code,des)
#by_product_melt %>% filter(variable %in% g5$des)

p1 <- df_cor %>% filter(product1 %in% g5$des) %>% filter(cor > 0.1) %>%  
           ggplot(aes(x=product1, y = product2, fill = cor)) + 
           geom_tile() + scale_fill_gradient(low="white", high="blue")  +
           theme_ipsum() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplotly(p1)

```

```{r}
e <- Sys.time()
print(e-s)
```
