library(tidyverse)
library(patchwork)
library(data.table) #fread
library(dplyr)
library(ggplot2)
library(MASS)
library(glmnet)
library(randomForest)
library(gbm)
library(rpart)
library(boot)
library(ROCR)
library(GGally)
library(reticulate)
library(aws.s3)
library(readr)
library(readxl)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(GGally)
library(knitr)
library(caret)
library(leaps)
library(stargazer)
library(ggpubr)
library(plotly)
library(kableExtra)

'%!in%' <- function(x,y)!('%in%'(x,y))