library(tidyverse)
library(patchwork)
library(data.table) #fread
library(dplyr)
library(ggplot2)
library(MASS)
library(glmnet)
library(randomForest)
library(gbm)
library(rpart)
library(boot)
library(ROCR)
library(GGally)
library(reticulate)
library(aws.s3)
library(readr)
library(readxl)
library(ggridges)
library(viridis)
library(hrbrthemes)
library(GGally)
library(knitr)
library(caret)
library(leaps)
library(stargazer)
library(ggpubr)
library(plotly)
library(kableExtra)

Sys.setenv(AWS_ACCESS_KEY_ID="ASIAV5MQ32FQIPZWDY5S",
           AWS_SECRET_ACCESS_KEY="Gk/n6cR9Mwkcxh17oC4+1dO3LX5siSGN3UNmV5ez",
           AWS_SESSION_TOKEN= "IQoJb3JpZ2luX2VjEPf//////////wEaCXVzLXdlc3QtMiJGMEQCICqhNKbhxXL4hoy/DwjDtH1BlomyuS+z2uPz4LmVnTItAiBhr5Jaif8AkC5Ns58TIdASIQjBs0kEqU2GEGAdYDHwnyqfAwiA//////////8BEAAaDDQwNjcxNTA5MzM0NCIMOVI68WAxWYLslMIqKvMCaN6jYtL81KPPyjos2X+Y6PQqF64hhX7TIBJPCGRpSBUW/T0zJcAOHlRbQbbCql0KJjv8dghKe+xP4fN/1FPXZqEtPKIoI2mj6N0WLn+7emcmaSW5Urg1rYgv9lP7l9IaVBrAZYCsIen2cf8jJrLTG6RtlgqBQNE4mnk6kVKShw+ZxZPhI6eOgL+mm5rJ95BjmyNuIetJ2ArZ9RfM/rJGwZMLwcidSPXWTdG2cQJ1b9bLHSM/cMtmKsP2cUAOQZBocYcQCa87aIUxlpOck/JzSNd6EmoWwAc74BBXeeGnfYek8zJSOK2skJLETlhXYHz0F4OZuc1/AXCXP8niwAE6phBzNytGPh4G7LRUWwstaY0E6cLUTHRz1dPbDzf4IGUW6jNURvMs/KNBoNLG0dtqB5MlNb7LJ9+exVFa1N6pu0BtJ87VWDrF3Hgyk5KJ1ndP9nZ1y8WECDXonFOcs6xdo+J6QmqSacOn6TDcINDR7tXLD/ow5Y/5kQY6pwEap2SXdpNOImy9B1923HkRWEgdno7CRsAdUgQu4ujNrhrPEe6Ir3iT6+5rQf2NuGr+j0+r33kIOP1hC2tKJF4MnnAs0NVcbfUghifVWrySSLR96E1RWd+rZxsOMkVnI7zDKhG3H68B49Hdpx+T1Qnci25EnGeupa/fNz8gRBXTYn1IJqFwxjpmqKKoAMkeVDngN5lYTGW7E3u4a7SbaoGheWkuiQmWQg==" 
)